apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/ip-allocated-from-pool: first-pool
  creationTimestamp: "2024-01-21T04:26:29Z"
  labels:
    app: istio-ingressgateway
    install.operator.istio.io/owning-resource: installed-state
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio: ingressgateway
    istio.io/rev: default
    operator.istio.io/component: IngressGateways
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.20.2
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
  resourceVersion: "5913161"
  uid: 650bc039-764c-4b8c-9c43-e50db0ef09e4
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.110.147.171
  clusterIPs:
  - 10.110.147.171
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: status-port
    nodePort: 31929
    port: 15021
    protocol: TCP
    targetPort: 15021
  - name: http2
    nodePort: 31971
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 30434
    port: 443
    protocol: TCP
    targetPort: 8443
  - name: tcp
    nodePort: 30266
    port: 31400
    protocol: TCP
    targetPort: 31400
  - name: tls
    nodePort: 32393
    port: 15443
    protocol: TCP
    targetPort: 15443
  - name: notice
    nodePort: 31380
    port: 2643
    protocol: TCP
    targetPort: 2643
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.168.55.100
