apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app
  name: notice-board
  labels:
    app: notice-board
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notice-board
  template:
    metadata:
      labels:
        app: notice-board
    spec:
      containers:
        - name: notice-board
          image: seoyoonho/notice-board:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 1000Mi